wandb_version: 1

data_normalization:
  desc: null
  value: 'True'
learning_rate:
  desc: null
  value: 0.01
batch_size:
  desc: null
  value: 64
epochs:
  desc: null
  value: 15
momentum:
  desc: null
  value: 0.8
kernel_size:
  desc: null
  value: 2
optimizer:
  desc: null
  value: SGD with momentum
dropout_rate:
  desc: null
  value: 0.4
l1_size:
  desc: null
  value: 256
l2_size:
  desc: null
  value: 128
batch_norm:
  desc: null
  value: 1
conv_1_size:
  desc: null
  value: 32
conv_2_size:
  desc: null
  value: 32
conv_3_size:
  desc: null
  value: 128
conv_4_size:
  desc: null
  value: 0
_wandb:
  desc: null
  value:
    python_version: 3.11.6
    cli_version: 0.16.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1708435467.358579
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 16
      - 23
      4: 3.11.6
      5: 0.16.3
      8:
      - 5
      13: linux-x86_64
