wandb_version: 1

learning_rate:
  desc: null
  value: 0.008
batch_size:
  desc: null
  value: 16
epochs:
  desc: null
  value: 15
momentum:
  desc: null
  value: 0.95
kernel_size:
  desc: null
  value: 3
optimizer:
  desc: null
  value: SGD with momentum
dropout_rate:
  desc: null
  value: 0
l1_size:
  desc: null
  value: 120
l2_size:
  desc: null
  value: 84
batch_norm:
  desc: null
  value: 1
_wandb:
  desc: null
  value:
    python_version: 3.11.6
    cli_version: 0.16.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1708428428.85742
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 16
      - 23
      4: 3.11.6
      5: 0.16.3
      8:
      - 5
      13: linux-x86_64
