wandb_version: 1

learning_rate:
  desc: null
  value: 0.01
batch_size:
  desc: null
  value: 16
epochs:
  desc: null
  value: 10
momentum:
  desc: null
  value: 0.9
kernel_size:
  desc: null
  value: 3
optimizer:
  desc: null
  value: Adam
_wandb:
  desc: null
  value:
    python_version: 3.11.6
    cli_version: 0.16.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1708426322.05226
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.11.6
      5: 0.16.3
      8:
      - 5
      13: linux-x86_64
